language: node_js
node_js: 
  - "9"
before_script:
  - npm run build

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npx jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
